//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeDecoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CakeDecoration()
        {
            this.SpecCakeDecoration = new HashSet<SpecCakeDecoration>();
        }
    
        public string Vendor_name { get; set; }
        public string Name { get; set; }
        public string Units { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Main_vendor { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string Weight { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecCakeDecoration> SpecCakeDecoration { get; set; }
    }
}
