//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredients()
        {
            this.SpecIngredients = new HashSet<SpecIngredients>();
        }
    
        public int Vendor_code { get; set; }
        public string Name { get; set; }
        public string Units { get; set; }
        public string Amount { get; set; }
        public string Main_vendor { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string GOST { get; set; }
        public string Packaging { get; set; }
        public string Characteristic { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecIngredients> SpecIngredients { get; set; }
    }
}
