//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public string Product { get; set; }
        public string Operation { get; set; }
        public int Serial_number { get; set; }
        public string Equiipment_type { get; set; }
        public int Time_for_operation { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
