//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Product { get; set; }
        public string User { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Plan_comp_date { get; set; }
        public byte[] Examples { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
