//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecIngredients
    {
        public string Product { get; set; }
        public int Ingredient { get; set; }
        public int Amount { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
