//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecCakeDecoration
    {
        public string Product { get; set; }
        public string Cake_decoration { get; set; }
        public int Amount { get; set; }
    
        public virtual CakeDecoration CakeDecoration { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
