//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools
    {
        public int Id { get; set; }
        public string ToolName { get; set; }
        public string ToolType { get; set; }
        public Nullable<System.DateTime> DateOfBuy { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Description { get; set; }
        public string Wear { get; set; }
        public string Provider { get; set; }
    }
}
